spring:

  application:
    name: appointment
    
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/appointment
    username: postgres
    password: 123456
  
  sql:
    init:
      mode: never
    
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    generate-ddl: true